# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:11-jdk
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: gradle assemble
  test:
    <<: *defaults
    steps:
      - checkout
      - run: gradle test
      - codecov/upload:
          file: build/reports/jacoco/test/jacocoTestReport.xml
          flags: coverage
  checkstyle:
    <<: *defaults
    steps:
      - checkout
      - run: gradle lintKotlinTest
  install:
    <<: *defaults
    steps:
      - checkout
      - run: gradle installDist

workflows:
  version: 2
  build-test-style-install:
    jobs:
      - build
      - test:
          requires:
            - build
      - checkstyle:
          requires:
            - build
      - install:
          requires:
            - test
            - checkstyle
