# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
 version: 2
 jobs:
   build:
     machine:
       image: circleci/classic:latest
     steps:
       - checkout
       - run: ./gradlew assemble
   test:
     machine:
       image: circleci/classic:latest
     steps:
       - checkout
       - run: ./gradlew test
   checkstyle:
     machine:
       image: circleci/classic:latest
     steps:
       - checkout
       - run: ./gradlew lintKotlinTest
       
 workflows:
   version: 2
   build-test-checkstyle:
     jobs:
       - build
       - test:
           requires:
             - build
       - checkstyle:
           requires:
               - test
