# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
 version: 2
 jobs:
   one:
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
       - checkout
       - run: echo "A first hello"
   two:
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
       - checkout
       - run: echo "A more familiar hi"
 workflows:
   version: 2
   one_and_two:
     jobs:
       - one
       - two
