# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#          
 version: 2
 jobs:
   branch:
     filters:
       branches:
         only:
           - master
   build:
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
       - checkout
       - run: gradle assemble
   test:
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
       - checkout
       - run: gradle test
   checkstyle:
     docker:
       - image: circleci/openjdk:11-jdk
     steps:
       - checkout
       - run: gradle lintKotlinTest
       
 workflows:
   version: 2
   build-test-checkstyle:
     jobs:
       - branch
       - build:
           requires:
             - branch
       - test:
           requires:
             - build
       - checkstyle:
           requires:
               - test
