# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#          
 version: 2.0
 defaults: &defaults
   working_directory: ~/repo
   docker:
     - image: circleci/openjdk:11-jdk
 jobs:
   build:
     <<: *defaults
     steps:
       - checkout
       - run: gradle assemble
       - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
   test:
     <<: *defaults
     steps:
       - checkout
       - run: gradle test
   checkstyle:
     <<: *defaults
     steps:
       - checkout
       - run: gradle lintKotlinTest
   install:
     <<: *defaults
     steps:
       - checkout
       - run: gradle installDist
       
 workflows:
   version: 2
   build-test-checkstyle:
     jobs:
       - build
       - test:
           requires:
             - build
       - checkstyle:
           requires:
               - build
       - install:
           requires:
             - test
             - checkstyle
