# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#          
 version: 2.0
 defaults: &defaults
   working_directory: ~/repo
   docker:
     - image: circleci/openjdk:11-jdk
 jobs:
   build:
     steps:
       - checkout
       - run: gradle assemble
   test:
     steps:
       - checkout
       - run: gradle test
   checkstyle:
     steps:
       - checkout
       - run: gradle lintKotlinTest
   install:
     steps:
       - checkout
       - run: gradle installDist
       
 workflows:
   version: 2
   build-test-checkstyle:
     jobs:
       - build
       - test:
           requires:
             - build
       - checkstyle:
           requires:
               - build
       - install:
           requires:
             - test
             - checkstyle
