# Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle dependencies
  
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run: gradle test

workflows:
  version: 2
    one_and_two:
      jobs:
        - dependencies
        - test
